apiVersion: v1
kind: Service
metadata:
  name: stock-analyzer
  namespace: apps
  labels:
    app.kubernetes.io/name: stock-analyzer
spec:
  type: LoadBalancer
  ports:
  - port: 8501
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: stock-analyzer
