apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    purpose: application-workloads
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    purpose: gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    purpose: observability
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
  labels:
    purpose: load-balancing
